# Configuração para EasyPanel com Heroku Buildpacks
# NOTA: O Procfile é usado automaticamente pelo buildpack
# Leia DEPLOY.md para instruções completas
name: evolutia-dashboard
services:
  - name: web
    type: app
    source:
      type: git
      url: # Seu repositório Git aqui
      branch: main
    build:
      type: buildpack
      buildpack: heroku/builder:24
    deploy:
      replicas: 1
      # O Procfile define o comando (migrations + start)
      # PORT é definida automaticamente pelo buildpack
      env:
        - name: NODE_ENV
          value: production
        # OBRIGATÓRIAS
        - name: DATABASE_URL
          value: # postgresql://user:pass@host:port/db
        - name: SESSION_SECRET
          value: # usar: openssl rand -base64 32
        - name: LOGIN
          value: # seu usuário admin
        - name: SENHA
          value: # sua senha admin
        # OPCIONAIS
        # - name: WebhookProposta
        #   value: https://your-webhook-url.com
        # - name: DatabaseLandingPage
        #   value: postgresql://user:pass@host:port/db
    domains:
      - host: # Seu domínio aqui
    resources:
      memory: 512Mi
      cpu: 0.5